// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.DataAccess.Concrete.EntityFramework;

#nullable disable

namespace NLayer.DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20220629121705_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Entity.Concrete.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Sude",
                            Password = "1234",
                            Username = "sudecom"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Eylem",
                            Password = "6547",
                            Username = "dataselek"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Eda",
                            Password = "1478",
                            Username = "eda12"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Canan",
                            Password = "2589",
                            Username = "cnn2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
